### PR TITLE
1.20.4 Neoforge

### PR DESCRIPTION
**Pull request by TheWinABagel**
All attributes were tested, they seem to all be working (Im *mostly* sure lava + water visibility are the same? I dont trust myself tho)
Some mixins were converted to events
And I wasnt sure what to do with water speed as neo already has a water speed attribute...

### CODE REVIEW

**Comment by DaFuqs** [comment]
> I wasnt sure what to do with water speed as neo already has a water speed attribute

In that case that one can be removed to assure compat between mods. Rest looks dope!

**Comment by ChrysanthCow** [comment]
Hmm, interesting, I'll definitely deprecate the current (Neo)Forge fork if necessary.

**Comment by DaFuqs** [comment]
> Hmm, interesting, I'll definitely deprecate the current (Neo)Forge fork if necessary.

I wonder how they compare. I thought Forge mods would not work on Neoforge?

**Comment by ChrysanthCow** [comment]
> > Hmm, interesting, I'll definitely deprecate the current (Neo)Forge fork if necessary.
> 
> I wonder how they compare. I thought Forge mods would not work on Neoforge?

The thing is, we have no use for Forge post 1.20.1, as Origins Forge is moving to NeoForge.

**Pull request merged**
