### PR TITLE
Added a MaxAir attribute

### PR DESCRIPTION
**Pull request by MayaqqDev**
:3

### CODE REVIEW

**Comment by Noaaan** [comment]
No lang files?

**Comment by apace100** [comment]
Isn't there a Water Breathing API library mod thing around which allows for this? If so, do they maybe have an attribute for this already?

Either way this would probably need to be compatible with that. :) Maybe it could even switch to that library's implementation if it is present!

**Comment by MayaqqDev** [comment]
> No lang files?

oh there is a lang file

**Review by DaFuqs — APPROVED** [review]
neat

**Pull request merged**
