### PR TITLE
[1.20.6] Scale related attributes

### PR DESCRIPTION
**Pull request by ChrysanthCow**
# This'll be a draft until 1.20.5 releases.
Adds these modifiers:

- WIDTH: Controls the width of the entity's hitbox and model.
- HEIGHT: Controls the height of the entity's hitbox and model.
- HITBOX_SCALE: Controls the scale of the entity's hitbox without changing the model's scale.
- MODEL_SCALE: Controls the scale of the entity's model without changing the hitbox's scale.
- HITBOX_WIDTH: Controls the width of the entity's hitbox.
- HITBOX_HEIGHT: Controls the height of the entity's hitbox.
- MODEL_WIDTH: Controls the width of the entity's hitbox.
- MODEL_HEIGHT: Controls the height of the entity's hitbox.
- MOB_DETECTION_RANGE: Controls the range at which hostile mobs will detect this entity.

### CODE REVIEW

**Comment by ChrysanthCow** [comment]
To confirm. Yes, I have talked to Pehkui's dev about this, and I've purposefully made it so we aren't stepping on what makes Pehkui unique going forth.

**Comment by DaFuqs** [comment]
Oops. Now that looks better.

**Comment by DaFuqs** [comment]
Love the MOB_DETECTION_RANGE addition!

Now, I am curious, what's the use-case of scaling like height, hitbox_height and model_height individually? Wouldn't it mess with the way the player expects the hitbox size matching the entities size and everything?

**Comment by ChrysanthCow** [comment]
> Love the MOB_DETECTION_RANGE addition!
> 
> Now, I am curious, what's the use-case of scaling like height, hitbox_height and model_height individually? Wouldn't it mess with the way the player expects the hitbox size matching the entities size and everything?

Some examples are: if people have a small entity and you want to make their hitbox slightly bigger to have an easier time hitting them. Or if you want to be slightly taller without a hitbox change that'd screw with going through the what the player would normally be able to go through.

**Comment by ChrysanthCow** [comment]
They are absolutely open to misuse, but that's something that any attribute can face. Devs should know what's fair and unfair.

**Comment by ChrysanthCow** [comment]
Point is, separate hitbox/model changes work best when subtle. The two points above are imo perfect examples of this. I think that you were thinking of it at a more drastic degree.

**Comment by Noaaan** [comment]
Bumping this PR as... 1.20.6 already released. :mojank:
Would probably be fine for release if the other commits from 1.20.4 are merged/cherry-picked in (d0e9b4d52a200589c8fad9b200095cd412c55d6d ?, 0150a518620aa05034a4ad52746a2a0b05809b4c, and 6f98ceda2e7bf3649c598aba4e813738cd8988dc). Will do some testing once available :+1:

**Comment by ChrysanthCow** [comment]
Go ahead.

**Comment by ChrysanthCow** [comment]
Okay, I'm nearly done with this PR. Just ironing out some final things.

Some things to keep in mind
- Scales below 0.5 will not update the camera's draw distance, so it can clip into blocks.
- I have not removed any of the no longer necessary attributes. The jump attribute could be removed but I left it in as imo it's your decision.

**Comment by DaFuqs** [comment]
Thank you! Have you tested this with vanilla's new `generic.scale`?

With 1.20.6 we can definitely revamp or remove another attribute or two, since there is now:
- `player.block_break_speed`
- `generic.jump_strength`

**Comment by DaFuqs** [comment]
I did a bit of cleanup in the current branch. I can fix the conflicts tomorrow.

**Comment by DaFuqs** [comment]
@MerchantPug I tried mixing vanillas `generic.scale` and `additionalentityattributes.height` and the camera weirded out quickly.
Can you take another look what would need to be changed to make both compatible? The vanilla camera code may have been revised in general, making the vanilla attribute work with all mobs. Maybe we do not even need all the mixins for individual mobs anymore?

**Comment by ChrysanthCow** [comment]
> @MerchantPug I tried mixing vanillas `generic.scale` and `additionalentityattributes.height` and the camera weirded out quickly. Can you take another look what would need to be changed to make both compatible? The vanilla camera code may have been revised in general, making the vanilla attribute work with all mobs. Maybe we do not even need all the mixins for individual mobs anymore?

Alright, I'll make sure to look into this at some point.

**Comment by ChrysanthCow** [comment]
@DaFuqs this has been fixed!

**Comment by ChrysanthCow** [comment]
Apologies for being so slow, I've been busy working on another mod.

**Comment by DaFuqs** [comment]
Thank you lots!

**Pull request merged**
